project:
  type: book
  output-dir: docs

filters:
  - shinylive

toc: true

number-depth: 2

book:
  title: "Strength of Materials Problem Exercises"
  author: "Curated by James Lord, Jake Grohs, ..."
  date: "1/5/2024"
  page-navigation: true
  search: true
  sidebar:
    style: docked
    collapse-level: 0
  
  chapters:
    - index.qmd
    - part: "List of Complete Problems"
      chapters:
        - problem138dynamicsubmit.qmd
        - problem139dynamicsubmit.qmd
        - problem144dynamicsubmit.qmd
        - problem146dynamicsubmit.qmd
        - problem153dynamicsubmit.qmd
        - problem156dynamicsubmit.qmd
        - problem157dynamicsubmit.qmd
        - problem164dynamicsubmit.qmd
        - problem165dynamicsubmit.qmd
        - problem166dynamicsubmit.qmd
    - part: "Interactive Interface Demo"
      chapters:
        - interfacedemo.qmd   
    - part: "List of Working Problems"
      chapters:
        - problem168dynamicsubmit.qmd
        - problem169dynamicsubmit.qmd
        - problem180dynamicsubmit.qmd
        - problem183dynamicsubmit.qmd
        - problem184dynamicsubmit.qmd
        - problem185dynamicsubmit.qmd
        - problem186dynamicsubmit.qmd
        - problem187dynamicsubmit.qmd
        - problem188dynamicsubmit.qmd
        - problem191dynamicsubmit.qmd
        - problem192dynamicsubmit.qmd
        - problem193dynamicsubmit.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    fontsize: "10pt"
    theme: 
      light: 
      - flatly
      - include/light.scss
      dark: 
      - darkly
      - include/dark.scss
  pdf:
    documentclass: scrreprt
  epub: 
    cover-image: cover.png



