project:
  type: book
  output-dir: docs

filters:
  - shinylive

toc: true

number-depth: 2

book:
  title: "Strength of Materials Problem Exercises"
  author: "Curated by James Lord, Jake Grohs, ..."
  date: "1/5/2024"
  page-navigation: true
  search: true
  sidebar:
    style: docked
    collapse-level: 0
  
  chapters:
    - index.qmd
    - part: "List of Complete Problems"
      chapters:
        - problem138dynamicsubmit.qmd
        - problem139dynamicsubmit.qmd
        - problem144dynamicsubmit.qmd
        - problem146dynamicsubmit.qmd
        - problem153dynamicsubmit.qmd
        - problem156dynamicsubmit.qmd
        - problem157dynamicsubmit.qmd
        - problem164dynamicsubmit.qmd
        - problem165dynamicsubmit.qmd
        - problem166dynamicsubmit.qmd
    - part: "Interactive Interface Demo"
      chapters:
        - interfacedemo.qmd   
    - part: "List of Working Problems"
      chapters:
        - problem168dynamicsubmit.qmd
        - problem169dynamicsubmit.qmd
        - problem180dynamicsubmit.qmd
        - problem183dynamicsubmit.qmd
        - problem184dynamicsubmit.qmd
        - problem185dynamicsubmit.qmd
        - problem186dynamicsubmit.qmd
        - problem187dynamicsubmit.qmd
        - problem188dynamicsubmit.qmd
        - problem191dynamicsubmit.qmd
        - problem192dynamicsubmit.qmd
        - problem193dynamicsubmit.qmd
        - problem194dynamicsubmit.qmd
        - problem204dynamicsubmit.qmd
        - problem205dynamicsubmit.qmd
        - problem206dynamicsubmit.qmd
        - problem208dynamicsubmit.qmd
        - problem213dynamicsubmit.qmd
        - problem216dynamicsubmit.qmd
        - problem222dynamicsubmit.qmd
        - problem223dynamicsubmit.qmd
        - problem224dynamicsubmit.qmd
        - problem225dynamicsubmit.qmd
        - problem226dynamicsubmit.qmd
        - problem246dynamicsubmit.qmd
        - problem247dynamicsubmit.qmd
        - problem248dynamicsubmit.qmd
        - problem249dynamicsubmit.qmd
        - problem250dynamicsubmit.qmd
        - problem265dynamicsubmit.qmd
        - problem266dynamicsubmit.qmd
        - problem267dynamicsubmit.qmd
        - problem268dynamicsubmit.qmd
        - problem269dynamicsubmit.qmd
        - problem270dynamicsubmit.qmd
        - problem273dynamicsubmit.qmd
        - problem274dynamicsubmit.qmd
        - problem276dynamicsubmit.qmd
        - problem278dynamicsubmit.qmd
        - problem287dynamicsubmit.qmd
        - problem288dynamicsubmit.qmd
        - problem289dynamicsubmit.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

comments:
  utterances:
    repo: jrgrohs/StrengthOfMaterialsExercises

format:
  html:
    fontsize: "10pt"
    theme: 
      light: 
      - flatly
      - include/light.scss
      dark: 
      - darkly
      - include/dark.scss
  pdf:
    documentclass: scrreprt
  epub: 
    cover-image: cover.png



