project:
  type: book
  output-dir: docs

filters:
  - shinylive

toc: true

number-depth: 2

book:
  title: "Strength of Materials Problem Exercises"
  author: "Curated by James Lord, Jake Grohs, ..."
  date: "1/5/2024"
  page-navigation: true
  search: true
  sidebar:
    style: docked
    collapse-level: 0
  
  chapters:
    - index.qmd
    - part: "Problem 1"
      chapters:
        - problem1static.qmd
        - problem1dynamicsubmit.qmd
        - interfacedemo.qmd
    - part: "Problem 391"
      chapters:
        - problem138dynamicsubmit.qmd
        - problem139dynamicsubmit.qmd
        - problem144dynamicsubmit.qmd
        - problem146dynamicsubmit.qmd
        - problem153dynamicsubmit.qmd
        - problem156dynamicsubmit.qmd
        - problem157dynamicsubmit.qmd
        - problem164dynamicsubmit.qmd
        - problem165dynamicsubmit.qmd
        - problem166dynamicsubmit.qmd
        - problem169dynamicsubmit.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    fontsize: "10pt"
    theme: 
      light: 
      - flatly
      - include/light.scss
      dark: 
      - darkly
      - include/dark.scss
  pdf:
    documentclass: scrreprt
  epub: 
    cover-image: cover.png



