project:
  type: book
  output-dir: docs

filters:
  - shinylive
 
toc: true

number-depth: 2

book:
  title: "Strength of Materials Problem Exercises"
  author: "Curated by James Lord, Jake Grohs, ..."
  date: "1/5/2024"
  page-navigation: true
  search: true
  sidebar:
    style: docked
    collapse-level: 0
  
  chapters:
    - index.qmd
    - part: "Chapter 2"
      chapters:
        - problem2_1dynamicsubmit.qmd
        - problem2_2dynamicsubmit.qmd
        - problem2_3dynamicsubmit.qmd
        - problem2_4dynamicsubmit.qmd
        - problem2_21dynamicsubmit.qmd
        - problem2_22dynamicsubmit.qmd
        - problem2_23dynamicsubmit.qmd
        - problem2_38dynamicsubmit.qmd
        - problem2_39dynamicsubmit.qmd
        - problem2_41dynamicsubmit.qmd
        - problem2_47dynamicsubmit.qmd
        - problem2_48dynamicsubmit.qmd
    - part: "Chapter 4"
      chapters:
        - problem4_5dynamicsubmit.qmd
        - problem4_6dynamicsubmit.qmd
        - problem4_10dynamicsubmit.qmd
        - problem4_11dynamicsubmit.qmd
        - problem4_12dynamicsubmit.qmd
        - problem4_23dynamicsubmit.qmd
        - problem4_24dynamicsubmit.qmd
        - problem4_25dynamicsubmit.qmd
        - problem4_35dynamicsubmit.qmd
    - part: "Chapter 5"
      chapters:
        - problem5_11dynamicsubmit.qmd
        - problem5_12dynamicsubmit.qmd
        - problem5_13dynamicsubmit.qmd
        - problem5_14dynamicsubmit.qmd
        - problem5_15dynamicsubmit.qmd
        - problem5_27dynamicsubmit.qmd
        - problem5_34dynamicsubmit.qmd
        - problem5_35dynamicsubmit.qmd
        - problem5_36dynamicsubmit.qmd
        - problem5_37dynamicsubmit.qmd
        - problem5_38dynamicsubmit.qmd
        - problem5_39dynamicsubmit.qmd
        - problem5_50dynamicsubmit.qmd
        - problem5_51dynamicsubmit.qmd
        - problem5_52dynamicsubmit.qmd
        - problem5_53dynamicsubmit.qmd
        - problem5_54dynamicsubmit.qmd
        - problem5_55dynamicsubmit.qmd
    - part: "Chapter 6"
      chapters:
        - problem6_1dynamicsubmit.qmd
        - problem6_2dynamicsubmit.qmd
        - problem6_3dynamicsubmit.qmd
        - problem6_4dynamicsubmit.qmd
        - problem6_5dynamicsubmit.qmd
        - problem6_11dynamicsubmit.qmd
        - problem6_12dynamicsubmit.qmd
        - problem6_13dynamicsubmit.qmd
        - problem6_14dynamicsubmit.qmd
        - problem6_15dynamicsubmit.qmd
        - problem6_27dynamicsubmit.qmd
    - part: "Problem Exercises (No App)"
      chapters:
        - problem2_1staticsubmit.qmd
        - problem2_2staticsubmit.qmd
        - problem2_3staticsubmit.qmd
        - problem2_4staticsubmit.qmd
        - problem2_21staticsubmit.qmd
        - problem2_22staticsubmit.qmd
        - problem2_23staticsubmit.qmd
        - problem2_38staticsubmit.qmd
        - problem2_39staticsubmit.qmd
        - problem2_41staticsubmit.qmd
        - problem2_47staticsubmit.qmd
        - problem2_48staticsubmit.qmd
        - problem4_5staticsubmit.qmd
        - problem4_6staticsubmit.qmd
        - problem4_10staticsubmit.qmd
        - problem4_11staticsubmit.qmd
        - problem4_12staticsubmit.qmd
        - problem4_23staticsubmit.qmd
        - problem4_24staticsubmit.qmd
        - problem4_25staticsubmit.qmd
        - problem4_35staticsubmit.qmd
        - problem5_11staticsubmit.qmd
        - problem5_12staticsubmit.qmd
        - problem5_13staticsubmit.qmd
        - problem5_14staticsubmit.qmd
        - problem5_15staticsubmit.qmd
        - problem5_27staticsubmit.qmd
        - problem5_34staticsubmit.qmd
        - problem5_35staticsubmit.qmd
    - part: "Interactive Interface Demo"
      chapters:
        - interfacedemo.qmd   
    - part: "List of Working Problems"
      chapters:
        - problem2_1dynamicsubmit.qmd
        - problem2_2dynamicsubmit.qmd
        - problem2_3dynamicsubmit.qmd
        - problem2_4dynamicsubmit.qmd
        - problem2_21dynamicsubmit.qmd
        - problem2_22dynamicsubmit.qmd
        - problem2_23dynamicsubmit.qmd
        - problem2_38dynamicsubmit.qmd
        - problem2_39dynamicsubmit.qmd
        - problem2_40dynamicsubmit.qmd
        - problem2_47dynamicsubmit.qmd
        - problem2_48dynamicsubmit.qmd
        - problem4_5dynamicsubmit.qmd
        - problem4_6dynamicsubmit.qmd
        - problem4_10dynamicsubmit.qmd
        - problem4_11dynamicsubmit.qmd
        - problem4_12dynamicsubmit.qmd
        - problem4_23dynamicsubmit.qmd
        - problem4_24dynamicsubmit.qmd
        - problem4_25dynamicsubmit.qmd
        - problem4_35dynamicsubmit.qmd
        - problem5_11dynamicsubmit.qmd
        - problem5_12dynamicsubmit.qmd
        - problem5_13dynamicsubmit.qmd
        - problem5_14dynamicsubmit.qmd
        - problem5_15dynamicsubmit.qmd
        - problem5_27dynamicsubmit.qmd
        - problem5_34dynamicsubmit.qmd
        - problem5_35dynamicsubmit.qmd
        - problem5_36dynamicsubmit.qmd
        - problem5_37dynamicsubmit.qmd
        - problem5_38dynamicsubmit.qmd
        - problem5_39dynamicsubmit.qmd
        - problem5_50dynamicsubmit.qmd
        - problem5_51dynamicsubmit.qmd
        - problem5_52dynamicsubmit.qmd
        - problem5_53dynamicsubmit.qmd
        - problem5_54dynamicsubmit.qmd
        - problem5_55dynamicsubmit.qmd
        - problem6_1dynamicsubmit.qmd
        - problem6_2dynamicsubmit.qmd
        - problem6_3dynamicsubmit.qmd
        - problem6_4dynamicsubmit.qmd
        - problem6_5dynamicsubmit.qmd
        - problem6_11dynamicsubmit.qmd
        - problem6_12dynamicsubmit.qmd
        - problem6_13dynamicsubmit.qmd
        - problem6_14dynamicsubmit.qmd
        - problem6_15dynamicsubmit.qmd
        - problem6_27dynamicsubmit.qmd
        - problem6_28dynamicsubmit.qmd
        - problem6_30dynamicsubmit.qmd
        - problem6_31dynamicsubmit.qmd
        - problem7_1dynamicsubmit.qmd
        - problem7_2dynamicsubmit.qmd
        - problem7_3dynamicsubmit.qmd
        - problem7_14dynamicsubmit.qmd
        - problem7_15dynamicsubmit.qmd
        - problem7_16dynamicsubmit.qmd
        - problem7_26dynamicsubmit.qmd
        - problem7_28dynamicsubmit.qmd
        - problem7_29dynamicsubmit.qmd
        - problem8_1dynamicsubmit.qmd
        - problem8_2dynamicsubmit.qmd
        - problem9_1dynamicsubmit.qmd
        - problem9_2dynamicsubmit.qmd
        - problem9_3dynamicsubmit.qmd
        - problem9_4dynamicsubmit.qmd
        - problem9_5dynamicsubmit.qmd
        - problem9_21dynamicsubmit.qmd
        - problem9_22dynamicsubmit.qmd
        - problem9_23dynamicsubmit.qmd
        - problem9_24dynamicsubmit.qmd
        - problem9_25dynamicsubmit.qmd
        - problem9_31dynamicsubmit.qmd
        - problem9_32dynamicsubmit.qmd
        - problem9_33dynamicsubmit.qmd
        - problem9_34dynamicsubmit.qmd
        - problem10_1dynamicsubmit.qmd
        - problem10_4dynamicsubmit.qmd
        - problem10_5dynamicsubmit.qmd
        - problem10_6dynamicsubmit.qmd
        - problem10_7dynamicsubmit.qmd
        - problem10_8dynamicsubmit.qmd
        - problem10_17dynamicsubmit.qmd
        - problem10_18dynamicsubmit.qmd
        - problem10_19dynamicsubmit.qmd
        - problem10_20dynamicsubmit.qmd
        - problem10_21dynamicsubmit.qmd
        - problem11_1dynamicsubmit.qmd
        - problem11_2dynamicsubmit.qmd
        - problem11_3dynamicsubmit.qmd
        - problem11_4dynamicsubmit.qmd
        - problem11_5dynamicsubmit.qmd
        - problem11_17dynamicsubmit.qmd
        - problem11_18dynamicsubmit.qmd
        - problem11_19dynamicsubmit.qmd
        - problem11_22dynamicsubmit.qmd
        - problem11_23dynamicsubmit.qmd
        - problem11_24dynamicsubmit.qmd
        - problem11_25dynamicsubmit.qmd
        - problem11_26dynamicsubmit.qmd
        - problem11_36dynamicsubmit.qmd
        - problem11_37dynamicsubmit.qmd
        - problem11_38dynamicsubmit.qmd
        - problem11_39dynamicsubmit.qmd
        - problem11_40dynamicsubmit.qmd
        - problem11_50dynamicsubmit.qmd
        - problem11_51dynamicsubmit.qmd
        - problem11_53dynamicsubmit.qmd
        - problem12_1dynamicsubmit.qmd
        - problem12_2dynamicsubmit.qmd
        - problem12_3dynamicsubmit.qmd
        - problem12_4dynamicsubmit.qmd
        - problem12_5dynamicsubmit.qmd
        - problem12_9dynamicsubmit.qmd
        - problem12_10dynamicsubmit.qmd
        - problem12_11dynamicsubmit.qmd
        - problem12_12dynamicsubmit.qmd
        - problem12_13dynamicsubmit.qmd
        - problem12_25dynamicsubmit.qmd
        - problem12_26dynamicsubmit.qmd
        - problem12_27dynamicsubmit.qmd
        - problem12_28dynamicsubmit.qmd
        - problem12_29dynamicsubmit.qmd
        - problem12_39dynamicsubmit.qmd
        - problem12_40dynamicsubmit.qmd
        - problem13_1dynamicsubmit.qmd
        - problem13_2dynamicsubmit.qmd
        - problem13_3dynamicsubmit.qmd
        - problem13_4dynamicsubmit.qmd
        - problem13_15dynamicsubmit.qmd
        - problem13_16dynamicsubmit.qmd
        - problem14_1dynamicsubmit.qmd
        - problem14_2dynamicsubmit.qmd
        - problem14_9dynamicsubmit.qmd
        - problem14_10dynamicsubmit.qmd
        - problem14_11dynamicsubmit.qmd
        - problem15_1dynamicsubmit.qmd
        - problem15_2dynamicsubmit.qmd
        - problem15_3dynamicsubmit.qmd
        - problem15_11dynamicsubmit.qmd
        - problem15_12dynamicsubmit.qmd
        - problem15_13dynamicsubmit.qmd
        - problem15_14dynamicsubmit.qmd
        - problem15_15dynamicsubmit.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

comments:
  utterances:
    repo: jrgrohs/StrengthOfMaterialsExercises

format:
  html:
    fontsize: "10pt"
    theme: 
      light: 
      - flatly
      - include/light.scss
      dark: 
      - darkly
      - include/dark.scss
  pdf:
    documentclass: scrreprt
  epub: 
    cover-image: cover.png



